In [8]:
from matplotlib import pyplot as plt
import pandas as pd
import seaborn as sns
%matplotlib inline
import warnings 
warnings.filterwarnings('ignore')

stats = pd.read_csv('C:\\Users\\nnagaraj\\Desktop\\Book1.csv')
stats


30 Year Moving Average Unnamed: 1   Unnamed: 2
0                     year  MA Global  MA Memphis 
1                     1779       8.14        15.28
2                     1780       8.16        15.09
3                     1781       8.16        15.05
4                     1782       8.24        15.22
5                     1783       8.21        15.20
6                     1784       8.19        15.18
7                     1785       8.16        15.23
8                     1786       8.14        15.22
9                     1787       8.11        15.22
10                    1788       8.16        15.28
11                    1789       8.17        15.29
12                    1790       8.20        15.35
13                    1791       8.18        15.34
14                    1792       8.16        15.33
15                    1793       8.19        15.40
16                    1794       8.19        15.41
17                    1795       8.20        15.43
18                    1796       8.19        15.41
19                    1797       8.20        15.43
20                    1798       8.26        15.49
21                    1799       8.29        15.50
22                    1800       8.32        15.52
23                    1801       8.34        15.52
24                    1802       8.36        15.53
25                    1803       8.37        15.53
26                    1804       8.37        15.55
27                    1805       8.35        15.53
28                    1806       8.35        15.55
29                    1807       8.35        15.56
..                     ...        ...          ...
218                   1996       8.84        16.29
219                   1997       8.85        16.29
220                   1998       8.89        16.37
221                   1999       8.91        16.43
222                   2000       8.93        16.46
223                   2001       8.95        16.47
224                   2002       8.99        16.49
225                   2003       9.01        16.48
226                   2004       9.04        16.50
227                   2005       9.07        16.52
228                   2006       9.11        16.59
229                   2007       9.14        16.62
230                   2008       9.16        16.65
231                   2009       9.19        16.68
232                   2010       9.21        16.70
233                   2011       9.22        16.73
234                   2012       9.25        16.78
235                   2013       9.27        16.86
236                    NaN        NaN          NaN
237                    NaN        NaN          NaN
238                    NaN        NaN          NaN
239                    NaN        NaN          NaN
240                    NaN        NaN          NaN
241                    NaN        NaN          NaN
242                    NaN        NaN          NaN
243                    NaN        NaN          NaN
244                    NaN        NaN          NaN
245                    NaN        NaN          NaN
246                    NaN        NaN          NaN
247                    NaN        NaN          NaN

[248 rows x 3 columns]

In [6]:
cast_names = ["Barney", "Robin", "Ted", "Lily", "Marshall"]
cast_heights = [72, 68, 72, 66, 76]

cast = dict(zip(cast_names, cast_heights))
print(cast)


{'Barney': 72, 'Robin': 68, 'Ted': 72, 'Lily': 66, 'Marshall': 76}


In [12]:
#Unzip the cast tuple into two names and heights tuples.

cast = (("Barney", 72), ("Robin", 68), ("Ted", 72), ("Lily", 66), ("Marshall", 76))

names, heights = zip(*cast)
print(names)
print(heights)

('Barney', 'Robin', 'Ted', 'Lily', 'Marshall')
(72, 68, 72, 66, 76)


In [15]:
#Use zip to transpose data from a 4-by-3 #matrix to a 3-by-4 matrix. There's actually a cool trick for this! Feel free to look at the solutions if you can't figure it out.

data = ((0, 1, 2), (3, 4, 5), (6, 7, 8), (9, 10, 11))

data_transpose = tuple(zip(*data))
print(data_transpose)

((0, 3, 6, 9), (1, 4, 7, 10), (2, 5, 8, 11))


In [31]:
#Use enumerate to modify the cast list so that each element contains the name followed by the character's corresponding height. For example, the first element of cast should change from "Barney Stinson" to "Barney Stinson 72".


cast = ["Barney Stinson", "Robin Scherbatsky", "Ted Mosby", "Lily Aldrin", "Marshall Eriksen"]
heights = [72, 68, 72, 66, 76]

# write your for loop here
for i, character in enumerate(cast):
    cast[i] = character + " " + str(heights[i])
print(cast)


['Barney Stinson 72', 'Robin Scherbatsky 68', 'Ted Mosby 72', 'Lily Aldrin 66', 'Marshall Eriksen 76']


In [32]:
### LIST COMPREHENSIONS###

In [35]:
#Use a list comprehension to create a new list first_names containing just the first names in names in lowercase.

names = ["Rick Sanchez", "Morty Smith", "Summer Smith", "Jerry Smith", "Beth Smith"]

first_names = [name.split()[0].lower() for name in names]
print(first_names)

['rick', 'morty', 'summer', 'jerry', 'beth']


In [43]:
#Use a list comprehension to create a list multiples_3 containing the first 20 multiples of 3.


multiples_3 = [3*x for x in range(1,21)]
print(multiples_3)




[3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57, 60]


In [50]:
#Use a list comprehension to create a list of names passed that only include those that scored at least 65.


scores = {
             "Rick Sanchez": 70,
             "Morty Smith": 35,
             "Summer Smith": 82,
             "Jerry Smith": 23,
             "Beth Smith": 98
          }

passed = [k for (k,v) in scores.items() if v >= 65]
print(passed)




['Rick Sanchez', 'Summer Smith', 'Beth Smith']


In [9]:
# write your function here
def readable_timedelta(num):
    day = num%7
    week = num//7
    return("{} week(s) and {} day(s)".format(week,day))
print(readable_timedelta(10))


1 week(s) and 3 day(s)


In [13]:
egg_count = 0

def buy_eggs():
    egg_count += 12 # purchase a dozen eggs
buy_eggs(0)

TypeError: buy_eggs() takes 0 positional arguments but 1 was given

In [14]:
###LAMBDA EXPRESSION###

In [15]:
"""MAP applies all the functions in the input list
map(function_to_apply, list_of_inputs)
    
    items = [1, 2, 3, 4, 5]                 squared = list(lambda(x:x**2,items))
    squared = []
    for i in items:
        squared.append(i**2)                   """


'MAP applies all the functions in the input list\nmap(function_to_apply, list_of_inputs)\n    \n    items = [1, 2, 3, 4, 5]                 squared = list(lambda(x:x**2,items))\n    squared = []\n    for i in items:\n        squared.append(i**2)                   '

In [24]:
def my_range(x):
    i = 5
    while i < x:
        yield i
        i += 1
        
for x in my_range(10):
    print(x)


5
6
7
8
9


In [29]:
range(20)
result = list(filter(lambda x: x<10, range(1,20,2)))
print(result)              

[1, 3, 5, 7, 9]


In [4]:
###ITERATORS###

lessons = ["Why Python Programming", "Data Types and Operators", "Control Flow", "Functions", "Scripting"]

def my_enumerate(iterable, start=0):
    count = start
    for element in iterable:
        yield count, element
        count +=1 

for i, lesson in my_enumerate(lessons, 1):
    print("Lesson {}: {}".format(i, lesson))

Lesson 1: Why Python Programming
Lesson 2: Data Types and Operators
Lesson 3: Control Flow
Lesson 4: Functions
Lesson 5: Scripting


In [5]:
###GENERATORS###

In [7]:
def chunker(iterable, size):
    for i in range(0, len(iterable), size):
        yield iterable[i:i + size]

for chunk in chunker(range(25), 4):
    print(list(chunk))


[0, 1, 2, 3]
[4, 5, 6, 7]
[8, 9, 10, 11]
[12, 13, 14, 15]
[16, 17, 18, 19]
[20, 21, 22, 23]
[24]


In [8]:
### EDITING A PYTHON SCRIPT ###

In [11]:
how_many_snakes = 1
snake_string = """
Welcome to Python3!

             ____
            / . .\\
            \  ---<
             \  /
   __________/ /
-=:___________/

<3, Juno
"""


print(snake_string * how_many_snakes)


Welcome to Python3!

             ____
            / . .\
            \  ---<
             \  /
   __________/ /
-=:___________/

<3, Juno



In [12]:
name = input('Enter a name')
print('Hello', name.title())

Enter a nameNagashri Nagaraj
Hello Nagashri Nagaraj


In [19]:
num = int(float(input('Please input a number: ')))
num += 20
print(num)

Please input a number: 2.3
22


In [23]:
result = eval(input("Please enter an expression that is bugging you!! "))
print("The answer that is playing hard to get is {}".format(result))

Please enter an expression that is bugging you!! 2**3
The answer that is playing hard to get is 8


In [37]:
"""

stu = []
stu.append(input("Enter Student's Name: "))
stu.append(float(input("Enter Total Missing Assignment: ")))
cur_grade = float(input("Enter Current Grade of Student: "))
stu.append((cur_grade + float(stu[1]) * 2))
print (stu)

"""

Enter Student's Name: fhg
Enter Total Missing Assignment: 4
Enter Current Grade of Student: 88
['fhg', 4.0, 96.0]


In [6]:

stu = [] 
while True:
    
    stu.append(input("Enter student's Name: "))
    stu.append(float(input("Enter Total Missing Assignment: ")))
    stu.append(float(input("Enter Current Grade of Student: ")) + float(stu[1] * 2))

    more = input("Another Student (Yes/No): ")
    
    if more.upper() != "YES":
        break
print(stu)

Enter student's Name: asds
Enter Total Missing Assignment: 12
Enter Current Grade of Student: 12
Another Student (Yes/No): yes
Enter student's Name: sdfsf
Enter Total Missing Assignment: 1.2
Enter Current Grade of Student: 1.2
Another Student (Yes/No): yes
Enter student's Name: oioj
Enter Total Missing Assignment: 54
Enter Current Grade of Student: 3
Another Student (Yes/No): no
['asds', 12.0, 36.0, 'sdfsf', 1.2, 25.2, 'oioj', 54.0, 27.0]


In [ ]:
##WORKING##

stu = {} 
while True:
    
    #name = ""
    name = input("Enter student's Name: ")
    if len(name) == 0:
        name = input("Enter student's Name: ")
        more = input("Do you want to exit? (Yes/No): ")
        if more.upper() == "YES":
            break
    
    missing_assignment = input("Enter Total Missing Assignment: ")
    current_grade = input("Enter Current Grade of Student: ")
    
    stu.update({name: (missing_assignment, (float(current_grade) + float(missing_assignment)*2))})

    more = input("Another Student (Yes/No): ")
    
    if more.upper() != "YES":
        break
print(stu)

Enter student's Name: as
Enter Total Missing Assignment: 1.2
Enter Current Grade of Student: 21
Another Student (Yes/No): yes
Enter student's Name: 
Enter student's Name: 
Do you want to exit? (Yes/No): y


In [5]:
stu['asd']

KeyError: 'asd'

In [5]:
#Dictionary

stu = {} 
while True:
        
    stu.update(name = input("Enter student's Name: "))
    stu.update(missing_assignment = input("Enter Total Missing Assignment: "))
    stu.update(current_grade = input("Enter Current Grade of Student: "))
       
    more = input("Another Student (Yes/No): ")
    
    if more.upper() != "YES":
        break
print(stu)

Enter student's Name: Jai
Enter Total Missing Assignment: 2
Enter Current Grade of Student: 88
Another Student (Yes/No): Yes
Enter student's Name: Ganesha
Enter Total Missing Assignment: 1
Enter Current Grade of Student: 99
Another Student (Yes/No): No
{'name': 'Ganesha', 'missing_assignment': '1', 'current_grade': '99'}


In [9]:
print(stu['current_grade'])

99


In [2]:
stu = {} 
while True:
    
  
    name = input("Enter student's Name: ")
    missing_assignment = input("Enter Total Missing Assignment: ")
    current_grade = input("Enter Current Grade of Student: ")
    
   
    
    stu.update({name: (missing_assignment, (float(current_grade) + float(missing_assignment)*2))})

    more = input("Another Student (Yes/No): ")
    
    if more.upper() != "YES":
        break
print(stu)

Enter student's Name: 
Enter Total Missing Assignment: 1
Enter Current Grade of Student: 2
Another Student (Yes/No): c
{'': ('1', 4.0)}


In [59]:
import numpy as np

# First 20 countries with employment data
countries = np.array([
    'Afghanistan', 'Albania', 'Algeria', 'Angola', 'Argentina',
    'Armenia', 'Australia', 'Austria', 'Azerbaijan', 'Bahamas',
    'Bahrain', 'Bangladesh', 'Barbados', 'Belarus', 'Belgium',
    'Belize', 'Benin', 'Bhutan', 'Bolivia',
    'Bosnia and Herzegovina'
])

# Employment data in 2007 for those 20 countries
employment = np.array([
    55.70000076,  51.40000153,  50.5       ,  75.69999695,
    58.40000153,  40.09999847,  61.5       ,  57.09999847,
    60.90000153,  66.59999847,  60.40000153,  68.09999847,
    66.90000153,  53.40000153,  48.59999847,  56.79999924,
    71.59999847,  58.40000153,  70.40000153,  41.20000076
])


#print(max(employment))   
#print(max(countries))


def max_employment(countries, employment):
    i = employment.argmax()
    return(countries[i], employment[i])

print(max_employment(countries, employment))



('Angola', 75.699996949999999)


In [26]:
print(countries.dtype)

<U22


In [27]:
print(employment.mean())

58.6850000385


In [31]:
from statistics import mode
mode(employment)

58.400001529999997

In [54]:
# First 20 countries with school completion data
countries = np.array([
       'Algeria', 'Argentina', 'Armenia', 'Aruba', 'Austria','Azerbaijan',
       'Bahamas', 'Barbados', 'Belarus', 'Belgium', 'Belize', 'Bolivia',
       'Botswana', 'Brunei', 'Bulgaria', 'Burkina Faso', 'Burundi',
       'Cambodia', 'Cameroon', 'Cape Verde'
])

# Female school completion rate in 2007 for those 20 countries
female_completion = np.array([
    97.35583,  104.62379,  103.02998,   95.14321,  103.69019,
    98.49185,  100.88828,   95.43974,   92.11484,   91.54804,
    95.98029,   98.22902,   96.12179,  119.28105,   97.84627,
    29.07386,   38.41644,   90.70509,   51.7478 ,   95.45072
])

# Male school completion rate in 2007 for those 20 countries
male_completion = np.array([
     95.47622,  100.66476,   99.7926 ,   91.48936,  103.22096,
     97.80458,  103.81398,   88.11736,   93.55611,   87.76347,
    102.45714,   98.73953,   92.22388,  115.3892 ,   98.70502,
     37.00692,   45.39401,   91.22084,   62.42028,   90.66958
])

def overall_completion_rate(female_completion, male_completion):
    '''
    Fill in this function to return a NumPy array containing the overall
    school completion rate for each country. The arguments are NumPy
    arrays giving the female and male completion of each country in
    the same order.
    '''
    
    return ((female_completion + male_completion)/2.0)

f_c = np.array(female_completion)
m_c = np.array(male_completion)

print(overall_completion_rate(f_c, m_c))


[  96.416025  102.644275  101.41129    93.316285  103.455575   98.148215
  102.35113    91.77855    92.835475   89.655755   99.218715   98.484275
   94.172835  117.335125   98.275645   33.04039    41.905225   90.962965
   57.08404    93.06015 ]


In [60]:
import math
math.sqrt(3.7)

1.9235384061671346

In [4]:
import numpy as np

# First 20 countries with employment data
countries = np.array([
    'Afghanistan', 'Albania', 'Algeria', 'Angola', 'Argentina',
    'Armenia', 'Australia', 'Austria', 'Azerbaijan', 'Bahamas',
    'Bahrain', 'Bangladesh', 'Barbados', 'Belarus', 'Belgium',
    'Belize', 'Benin', 'Bhutan', 'Bolivia',
    'Bosnia and Herzegovina'
])

# Employment data in 2007 for those 20 countries
employments = np.array([
    55.70000076,  51.40000153,  50.5       ,  75.69999695,
    58.40000153,  40.09999847,  61.5       ,  57.09999847,
    60.90000153,  66.59999847,  60.40000153,  68.09999847,
    66.90000153,  53.40000153,  48.59999847,  56.79999924,
    71.59999847,  58.40000153,  70.40000153,  41.20000076
])

# Change this country name to change what country will be printed when you
# click "Test Run". Your function will be called to determine the standardized
# score for this country for each of the given 5 Gapminder variables in 2007.
# The possible country names are available in the Downloadables section.

country_name = 'United States'

def standardized_data(values):
    standardized_values = (values-values.mean())/values.std()
    return standardized_values

standardized_data(employments)

array([-0.31965231, -0.780123  , -0.87650077,  1.82207181, -0.03051941,
       -1.99019768,  0.30144772, -0.16973184,  0.23719615,  0.84758731,
        0.18365304,  1.00821665,  0.87971351, -0.56595055, -1.07996476,
       -0.20185762,  1.38301845, -0.03051941,  1.2545153 , -1.87240259])

In [7]:
# Using index arrays

a = np.array([1, 2, 3, 4])
b = np.array([True, True, False, False])
    
print(a[b])
print(a[np.array([True, False, True, False])])

[1 2]
[1 3]


In [8]:
# Creating the index array using vectorized operations

a = np.array([1, 2, 3, 2, 1])
b = (a >= 2)
    
print(a[b])
print(a[a >= 2])

[2 3 2]
[2 3 2]


In [10]:
# Creating the index array using vectorized operations on another array

a = np.array([1, 2, 3, 4, 5])
b = np.array([1, 2, 3, 2, 1])
    
print(b == 2)
print(a[b == 2])  ##ARRAY OF a WHERE VALUE OF b == 2###

[False  True False  True False]
[2 4]


In [14]:
'''
    Fill in this function to calculate the mean time spent in the classroom
    for students who stayed enrolled at least (greater than or equal to) 7 days.
    Unlike in Lesson 1, you can assume that days_to_cancel will contain only
    integers (there are no students who have not canceled yet).
    
    The arguments are NumPy arrays. time_spent contains the amount of time spent
    in the classroom for each student, and days_to_cancel contains the number
    of days until each student cancel. The data is given in the same order
    in both arrays.
    '''

# Time spent in the classroom in the first week for 20 students
time_spent = np.array([
       12.89697233,    0.        ,   64.55043217,    0.        ,
       24.2315615 ,   39.991625  ,    0.        ,    0.        ,
      147.20683783,    0.        ,    0.        ,    0.        ,
       45.18261617,  157.60454283,  133.2434615 ,   52.85000767,
        0.        ,   54.9204785 ,   26.78142417,    0.
])

# Days to cancel for 20 students
days_to_cancel = np.array([
      4,   5,  37,   3,  12,   4,  35,  38,   5,  37,   3,   3,  68,
     38,  98,   2, 249,   2, 127,  35
])

def mean_time(time_spent, days_to_calcel):
    return (time_spent[days_to_cancel>=7]).mean()

print(mean_time(time_spent, days_to_cancel))



41.0540034855


In [22]:
a = np.array([1,2,3,4])
b = a
#a += np.array([1,1,1,1])
#print(b)
a = a + np.array([1,1,1,1])
print(b)

[1 2 3 4]


In [23]:
## In-Place Vs. Not In-Place

a = np.array([1,2,3,4,5])
slice = a[:3]
slice[0] = 100
print(a)

## Slice of an array is a view of the original array, any changes made to the slice, will be on the original array.



[100   2   3   4   5]


In [52]:
import pandas as pd
import numpy as np

countries = ['Albania', 'Algeria', 'Andorra', 'Angola', 'Antigua and Barbuda',
             'Argentina', 'Armenia', 'Australia', 'Austria', 'Azerbaijan',
             'Bahamas', 'Bahrain', 'Bangladesh', 'Barbados', 'Belarus',
             'Belgium', 'Belize', 'Benin', 'Bhutan', 'Bolivia']

life_expectancy_values = [74.7,  75. ,  83.4,  57.6,  74.6,  75.4,  72.3,  81.5,  80.2,
                          70.3,  72.1,  76.4,  68.1,  75.2,  69.8,  79.4,  70.8,  62.7,
                          67.3,  70.6]

gdp_values = [ 1681.61390973,   2155.48523109,  21495.80508273,    562.98768478,
              13495.1274663 ,   9388.68852258,   1424.19056199,  24765.54890176,
              27036.48733192,   1945.63754911,  21721.61840978,  13373.21993972,
                483.97086804,   9783.98417323,   2253.46411147,  25034.66692293,
               3680.91642923,    366.04496652,   1175.92638695,   1132.21387981]


def variable_correlation(variable1, variable2):
    both_above = (variable1 > variable1.mean()) & (variable2 > variable2.mean())
                 
    both_below = (variable1 < variable1.mean()) & (variable2 < variable2.mean())
                 
    is_same_direction = both_above | both_below
    
    num_same_direction = is_same_direction.sum()
    num_different_directon = len(variable1) - num_same_direction
    
    return(num_same_direction, num_different_directon)

life_expectancy = pd.Series(life_expectancy_values)
gdp = pd.Series(gdp_values)

variable_correlation(life_expectancy, gdp)                 

(17, 3)

In [53]:
# Addition when indexes are the same

s1 = pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])
s2 = pd.Series([10, 20, 30, 40], index=['a', 'b', 'c', 'd'])
print(s1 + s2)

a    11
b    22
c    33
d    44
dtype: int64


In [54]:
# Indexes have same elements in a different order

s1 = pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])
s2 = pd.Series([10, 20, 30, 40], index=['b', 'd', 'a', 'c'])
print(s1 + s2)

a    31
b    12
c    43
d    24
dtype: int64


In [5]:
import pandas as pd
s1 = pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])
s2 = pd.Series([10, 20, 30, 40], index=['c', 'd', 'e', 'f'])
#print(s1+s2)
p = (s1 + s2).fillna(0)
#p.dropna()
#p.fillna(0)
print(p)

a     0.0
b     0.0
c    13.0
d    24.0
e     0.0
f     0.0
dtype: float64


In [57]:
s1 = pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])
s2 = pd.Series([10, 20, 30, 40], index=['e', 'f', 'g', 'h'])
print(s1 + s2)

a   NaN
b   NaN
c   NaN
d   NaN
e   NaN
f   NaN
g   NaN
h   NaN
dtype: float64


In [15]:
import pandas as pd

s1 = pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])
s2 = pd.Series([10, 20, 30, 40], index=['c', 'd', 'e', 'f'])


print((s1 + s2).fillna(0))


# Try to write code that will add the 2 previous series together,
# but treating missing values from either series as 0. The result
# when printed out should be similar to the following line:
# print pd.Series([1, 2, 13, 24, 30, 40], index=['a', 'b', 'c', 'd', 'e', 'f'])

a     0.0
b     0.0
c    13.0
d    24.0
e     0.0
f     0.0
dtype: float64


In [21]:
### APPLY IN PANDAS ###

def clean_state(state):
    if len(state)==2:
        return state
    elif state == "Alabama":
        return 'AL'
    elif state == "Arkansas":
        return 'AR'
states = ['Al', 'Arkansas']    
states =  pd.Series(states)
clean_states = states.apply(clean_state)
print(clean_states)

0    Al
1    AR
dtype: object


In [46]:
name = 'Jerry Seienfield'
name.split(" ")

['Jerry', 'Seienfield']

In [63]:
def reverse_name(name):
    split_name = name.split(" ")
    first_name = split_name[0]
    last_name = split_name[1]
    return last_name + ", " + first_name

names = ['Andre Agassi', 'Barry Bonds', 'Daniel Craig']
names = pd.Series(names)
reverse_names = names.apply(reverse_name)
print(reverse_names)

0    Agassi, Andre
1     Bonds, Barry
2    Craig, Daniel
dtype: object


In [64]:
import numpy as np

# Subway ridership for 5 stations on 10 different days
ridership = np.array([
    [   0,    0,    2,    5,    0],
    [1478, 3877, 3674, 2328, 2539],
    [1613, 4088, 3991, 6461, 2691],
    [1560, 3392, 3826, 4787, 2613],
    [1608, 4802, 3932, 4477, 2705],
    [1576, 3933, 3909, 4979, 2685],
    [  95,  229,  255,  496,  201],
    [   2,    0,    1,   27,    0],
    [1438, 3785, 3589, 4174, 2215],
    [1342, 4043, 4009, 4665, 3033]
])

In [66]:
# Accessing elements

print(ridership[1, 3])
print(ridership[1:3, 3:5])
print(ridership[1, :])

2328
[[2328 2539]
 [6461 2691]]
[1478 3877 3674 2328 2539]


In [67]:
# Vectorized operations on rows or columns
print(ridership[0, :] + ridership[1, :])
print(ridership[:, 0] + ridership[:, 1])

[1478 3877 3676 2333 2539]
[   0 5355 5701 4952 6410 5509  324    2 5223 5385]


In [69]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([[1, 1, 1], [2, 2, 2], [3, 3, 3]])
print(a + b)

[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]]


In [73]:
print(ridership)

[[   0    0    2    5    0]
 [1478 3877 3674 2328 2539]
 [1613 4088 3991 6461 2691]
 [1560 3392 3826 4787 2613]
 [1608 4802 3932 4477 2705]
 [1576 3933 3909 4979 2685]
 [  95  229  255  496  201]
 [   2    0    1   27    0]
 [1438 3785 3589 4174 2215]
 [1342 4043 4009 4665 3033]]


In [80]:
## maxriders on 1st day ##
i = (ridership[0, :].argmax())
print(ridership[0,i])

5


In [82]:
## mean riders per day for that station ###
import math
mean_station = ridership[:,i].mean()
print(mean_station)

3239.9


In [84]:
mean_overall = ridership.mean()
print(mean_overall)

2342.6


In [86]:
def mean_riders_for_max_station(ridership):
  
    overall_mean = ridership.mean()
    i = ridership[0, :].argmax()
    mean_for_max = ridership[:,i].mean()
    
    return (overall_mean, mean_for_max)

mean_riders_for_max_station(ridership)

(2342.5999999999999, 3239.9000000000001)

In [87]:
 a = np.array([
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ])

In [91]:
print(a.sum())
print(a.sum(axis=0))
print(a.sum(axis=1))
print(a[:,0].sum())

45
[12 15 18]
[ 6 15 24]
12


In [92]:
print(ridership)

[[   0    0    2    5    0]
 [1478 3877 3674 2328 2539]
 [1613 4088 3991 6461 2691]
 [1560 3392 3826 4787 2613]
 [1608 4802 3932 4477 2705]
 [1576 3933 3909 4979 2685]
 [  95  229  255  496  201]
 [   2    0    1   27    0]
 [1438 3785 3589 4174 2215]
 [1342 4043 4009 4665 3033]]


In [98]:
## Mean ridership per day for each station

mean_ridership_station = ridership.mean(axis=0)
print(mean_ridership_station)
print(mean_ridership_station.min())
print(mean_ridership_station.max())

[ 1071.2  2814.9  2718.8  3239.9  1868.2]
1071.2
3239.9


In [99]:
import pandas as pd

# Subway ridership for 5 stations on 10 different days
ridership_df = pd.DataFrame(
    data=[[   0,    0,    2,    5,    0],
          [1478, 3877, 3674, 2328, 2539],
          [1613, 4088, 3991, 6461, 2691],
          [1560, 3392, 3826, 4787, 2613],
          [1608, 4802, 3932, 4477, 2705],
          [1576, 3933, 3909, 4979, 2685],
          [  95,  229,  255,  496,  201],
          [   2,    0,    1,   27,    0],
          [1438, 3785, 3589, 4174, 2215],
          [1342, 4043, 4009, 4665, 3033]],
    index=['05-01-11', '05-02-11', '05-03-11', '05-04-11', '05-05-11',
           '05-06-11', '05-07-11', '05-08-11', '05-09-11', '05-10-11'],
    columns=['R003', 'R004', 'R005', 'R006', 'R007']
)

In [100]:
 # You can create a DataFrame out of a dictionary mapping column names to values
df_1 = pd.DataFrame({'A': [0, 1, 2], 'B': [3, 4, 5]})
print(df_1)

   A  B
0  0  3
1  1  4
2  2  5


In [101]:
df_2 = pd.DataFrame([[0, 1, 2], [3, 4, 5]], columns=['A', 'B', 'C'])
print(df_2)

   A  B  C
0  0  1  2
1  3  4  5


In [103]:
ridership_df

R003  R004  R005  R006  R007
05-01-11     0     0     2     5     0
05-02-11  1478  3877  3674  2328  2539
05-03-11  1613  4088  3991  6461  2691
05-04-11  1560  3392  3826  4787  2613
05-05-11  1608  4802  3932  4477  2705
05-06-11  1576  3933  3909  4979  2685
05-07-11    95   229   255   496   201
05-08-11     2     0     1    27     0
05-09-11  1438  3785  3589  4174  2215
05-10-11  1342  4043  4009  4665  3033

In [106]:
print(ridership_df.iloc[0])
print(ridership_df.loc['05-05-11'])
print(ridership_df['R003'])
print(ridership_df.iloc[1, 3])
print(ridership_df.iloc[1:4])
print(ridership_df[['R003', 'R005']])

R003    0
R004    0
R005    2
R006    5
R007    0
Name: 05-01-11, dtype: int64
R003    1608
R004    4802
R005    3932
R006    4477
R007    2705
Name: 05-05-11, dtype: int64
05-01-11       0
05-02-11    1478
05-03-11    1613
05-04-11    1560
05-05-11    1608
05-06-11    1576
05-07-11      95
05-08-11       2
05-09-11    1438
05-10-11    1342
Name: R003, dtype: int64
2328
          R003  R004  R005  R006  R007
05-02-11  1478  3877  3674  2328  2539
05-03-11  1613  4088  3991  6461  2691
05-04-11  1560  3392  3826  4787  2613
          R003  R005
05-01-11     0     2
05-02-11  1478  3674
05-03-11  1613  3991
05-04-11  1560  3826
05-05-11  1608  3932
05-06-11  1576  3909
05-07-11    95   255
05-08-11     2     1
05-09-11  1438  3589
05-10-11  1342  4009


In [111]:
df = pd.DataFrame({'A': [0, 1, 2], 'B': [3, 4, 5]})
print(df)
print(df.sum())
print(df.sum(axis=1))
print(df.values.sum())

   A  B
0  0  3
1  1  4
2  2  5
A     3
B    12
dtype: int64
0    3
1    5
2    7
dtype: int64
15


In [123]:
ridership_df = pd.DataFrame(
    data = [[   0,    0,    2,    5,    0],
       [1478, 3877, 3674, 2328, 2539],
       [1613, 4088, 3991, 6461, 2691],
       [1560, 3392, 3826, 4787, 2613],
       [1608, 4802, 3932, 4477, 2705],
       [1576, 3933, 3909, 4979, 2685],
       [  95,  229,  255,  496,  201],
       [   2,    0,    1,   27,    0],
       [1438, 3785, 3589, 4174, 2215],
       [1342, 4043, 4009, 4665, 3033]],
    columns = ['station1', 'station2', 'station3', 'station4', 'station5'],
    index = ['day1', 'day2', 'day3', 'day4', 'day5', 'day6', 'day7', 'day8', 'day9', 'day10'])
ridership_df

station1  station2  station3  station4  station5
day1          0         0         2         5         0
day2       1478      3877      3674      2328      2539
day3       1613      4088      3991      6461      2691
day4       1560      3392      3826      4787      2613
day5       1608      4802      3932      4477      2705
day6       1576      3933      3909      4979      2685
day7         95       229       255       496       201
day8          2         0         1        27         0
day9       1438      3785      3589      4174      2215
day10      1342      4043      4009      4665      3033

In [131]:
#ridership_df.iloc[0].argmax()
max_rider_station = ridership_df.iloc[0].idxmax()
mean_for_max = ridership_df['station4'].mean()
overall_mean = ridership_df.values.mean()
print(overall_mean)

2342.6


In [112]:



def mean_riders_for_max_station(ridership):
    '''
    Fill in this function to find the station with the maximum riders on the
    first day, then return the mean riders per day for that station. Also
    return the mean ridership overall for comparsion.
    
    This is the same as a previous exercise, but this time the
    input is a Pandas DataFrame rather than a 2D NumPy array.
    '''
    overall_mean = None # Replace this with your code
    mean_for_max = None # Replace this with your code
    
    return (overall_mean, mean_for_max)

In [4]:
# Adding DataFrames with the column names
import pandas as pd
    
df1 = pd.DataFrame({'a': [1, 2, 3], 'b': [4, 5, 6], 'c': [7, 8, 9]})
df2 = pd.DataFrame({'a': [10, 20, 30], 'b': [40, 50, 60], 'c': [70, 80, 90]})
print(df1 + df2)

    a   b   c
0  11  44  77
1  22  55  88
2  33  66  99


In [6]:
# Adding DataFrames with overlapping column names 

df1 = pd.DataFrame({'a': [1, 2, 3], 'b': [4, 5, 6], 'c': [7, 8, 9]})
df2 = pd.DataFrame({'d': [10, 20, 30], 'c': [40, 50, 60], 'b': [70, 80, 90]})
print(df1 + df2)


    a   b   c   d
0 NaN  74  47 NaN
1 NaN  85  58 NaN
2 NaN  96  69 NaN


In [7]:
# Adding DataFrames with overlapping row indexes

df1 = pd.DataFrame({'a': [1, 2, 3], 'b': [4, 5, 6], 'c': [7, 8, 9]},
                       index=['row1', 'row2', 'row3'])
df2 = pd.DataFrame({'a': [10, 20, 30], 'b': [40, 50, 60], 'c': [70, 80, 90]},
                       index=['row4', 'row3', 'row2'])
print(df1 + df2)

         a     b     c
row1   NaN   NaN   NaN
row2  32.0  65.0  98.0
row3  23.0  56.0  89.0
row4   NaN   NaN   NaN


In [23]:
# Cumulative entries and exits for one station for a few hours.
entries_and_exits = pd.DataFrame({
    'ENTRIESn': [3144312, 3144335, 3144353, 3144424, 3144594,
                 3144808, 3144895, 3144905, 3144941, 3145094],
    'EXITSn': [1088151, 1088159, 1088177, 1088231, 1088275,
               1088317, 1088328, 1088331, 1088420, 1088753]
})

def get_hourly_entries_and_exits(entries_and_exits):
    '''
    Fill in this function to take a DataFrame with cumulative entries
    and exits (entries in the first column, exits in the second) and
    return a DataFrame with hourly entries and exits (entries in the
    first column, exits in the second).
    '''
    return None

entries_and_exits_diff = entries_and_exits.diff()

In [9]:
entries_and_exits

ENTRIESn   EXITSn
0   3144312  1088151
1   3144335  1088159
2   3144353  1088177
3   3144424  1088231
4   3144594  1088275
5   3144808  1088317
6   3144895  1088328
7   3144905  1088331
8   3144941  1088420
9   3145094  1088753

In [24]:
# DataFrame applymap()

df = pd.DataFrame({
'a': [1, 2, 3],
'b': [10, 20, 30],
'c': [5, 10, 15]
})
    
def add_one(x):
    return x + 1
        
print(df.applymap(add_one))

   a   b   c
0  2  11   6
1  3  21  11
2  4  31  16


In [45]:
grades_df = pd.DataFrame(
    data={'exam1': [43, 81, 78, 75, 89, 70, 91, 65, 98, 87],
          'exam2': [24, 63, 56, 56, 67, 51, 79, 46, 72, 60]},
    index=['Andre', 'Barry', 'Chris', 'Dan', 'Emilio', 
           'Fred', 'Greta', 'Humbert', 'Ivan', 'James']
)
    
def convert_grade(grade):
        if grade >= 90:
            return 'A'
        elif grade >= 89:
            return 'B'
        elif grade >= 79:
            return 'C'
        elif grade >= 69:
            return 'D'
        else:
            return 'F'
        
#grades_df.applymap(convert_grade)  

def convert_grades(grades):
    return grades.applymap(convert_grade)

convert_grades(grades_df)
    
   

exam1 exam2
Andre       F     F
Barry       C     F
Chris       D     F
Dan         D     F
Emilio      B     F
Fred        D     F
Greta       A     C
Humbert     F     F
Ivan        A     D
James       C     F